

use 50days_mysql;


/*
1.Question: Find products sold in the highest quantity.
2.Question: Find the least selling products.
3.Question: Find revenue generated by each product.
4.Question: Find total sales for each category.
5.Question: Find the highest priced product that was sold.
6.Question: Find average product price category-wise.
7.Question: Find daily quantity sold for each product.
*/



SELECT p.product_id,
    p.product_name,
    sum(od.qunatity) as highest_quantity
FROM cleaned_products P
    join cleaned_order_details od 
    ON p.product_id = od.product_id
GROUP BY p.product_id,
    p.product_name
ORDER BY highest_quantity DESC


SELECT p.product_id,
    p.product_name,
    sum(od.qunatity) as least_quantity
FROM cleaned_products P
    join cleaned_order_details od 
    ON p.product_id = od.product_id
GROUP BY p.product_id,
    p.product_name
ORDER BY least_quantity asc


SELECT p.product_id,
    p.product_name,
    SUM(od.qunatity * p.price) as revenue
FROM cleaned_products P
    join cleaned_order_details od 
    ON p.product_id = od.product_id
GROUP BY p.product_id,
    p.product_name
ORDER BY revenue DESC


SELECT p.category,
    SUM(p.price * od.qunatity) as categorywise_sales
FROM cleaned_products P
    join cleaned_order_details od 
    ON p.product_id = od.product_id
GROUP BY p.category
ORDER BY categorywise_sales DESC


SELECT distinct p.product_id,
    p.product_name,p.category,
    p.price
FROM cleaned_products P
    join cleaned_order_details od ON p.product_id = od.product_id
ORDER BY p.price DESC
LIMIT 1


SELECT p.category,
    avg(p.price) as categorywise_productprice
FROM cleaned_products P
GROUP BY p.category
ORDER BY categorywise_productprice DESC


SELECT p.product_id,
    p.product_name,o.order_date,
    sum(od.qunatity) as daily_quantity_sold
FROM cleaned_products P
    join cleaned_order_details od 
    ON p.product_id = od.product_id
    join cleaned_orders o 
    on od.order_id = o.order_id
GROUP BY p.product_id,
    p.product_name, o.order_date
ORDER BY o.order_date,daily_quantity_sold DESC





