
use 50days_mysql

/*1.Question: Find total business revenue.*/

select sum(payment_amount) as revenue
from cleaned_payments

/*2.Question: Find daily revenue.*/

select payment_date,
    sum(payment_amount) as dialy_revenue
from cleaned_payments
group by payment_date
order by payment_date


/*3.Question: Find monthly revenue trend.*/

select MONTH(Payment_date) AS Month_Num,
    MONTHNAME(Payment_date) as Month_Name,
    sum(payment_amount) as monthly_revenue
from cleaned_payments
group by Month_Num,Month_Name
order by Month_Num,
    Month_Name

/*4.Question: Find revenue generated by each product.*/

    SELECT p.product_id,
    p.product_name,
    SUM(od.qunatity * p.price) as product_revenue
FROM cleaned_products P
    join cleaned_order_details od 
    ON p.product_id = od.product_id
GROUP BY p.product_id,
    p.product_name
ORDER BY product_revenue DESC

/*5.Question: Find customer-wise revenue.*/

SELECT C.customer_ID,
    C.customer_Name,
    SUM(payment_amount) as revenue_by_customer
from cleaned_customers c
    join cleaned_orders o on c.customer_ID = o.customer_ID
    join cleaned_payments P on o.order_id = p.order_id
group by c.customer_ID,
    c.customer_Name
order by revenue_by_customer DESC


/*6.Question: Find category-wise revenue.*/

SELECT p.category,
    SUM(p.price * od.qunatity) as categorywise_revenue
FROM cleaned_products P
    join cleaned_order_details od 
    ON p.product_id = od.product_id
GROUP BY p.category
ORDER BY categorywise_revenue DESC


/*7.Question: Find days generating highest revenue.*/

select payment_date,
    sum(payment_amount) as total_revenue
from cleaned_payments
group by payment_date
order by total_revenue DESC